### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [it4e/CHL#16]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [method_post_init](https://github.com/it4e/CHL/blob/9aa0e4dd2782b970c8ae4bf619cc7a3de82dd290/core/src/cgi.c#L47)
- [realloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/realloc.html) ⇒ [file_read_data](https://github.com/it4e/CHL/blob/9aa0e4dd2782b970c8ae4bf619cc7a3de82dd290/core/src/view.c#L73)

**Comment by it4e** [comment]
@elfring Yes that might be a good idea!

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/)?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in your software?

**Comment by elfring** [comment]
How will software development be continued around the affected functions?

**Comment by it4e** [comment]
@elfring I have corrected the issues regarding the malloc/realloc functions.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Avoiding unchecked return values?") a bit more.
Are there [a few update candidates left over](https://github.com/it4e/CHL/blob/37c896594b390f27dabdbfee45b7c0b3aa4d13b8/core/src/cgi.c#L47 "Update candidate: method_post_init()")?

**Comment by it4e** [comment]
@elfring I overloaded the malloc/realloc functions using a #define directive in "std.h", so no.

**Comment by elfring** [comment]
I imagine that an other programming approach would be safer for the selection of a memory allocation alternative.
