### ISSUE TITLE
license

### ISSUE THREAD

**Issue by laoshaw** [it4e/CHL#19]
followed a reddit post here and am interested, but the GPL3.0 for a _library_ drives me away, sigh.  any possibility to consider a different license?

**Comment by it4e** [comment]
@laoshaw what's the issue with GPL 3.0? Which would you recommend?

**Comment by laoshaw** [comment]
LGPL? MIT? BSD3? Apache?

Make a _library_ GPL3 (or for that matter, GPL2) will not encourage its wide usage I feel. Library is a bit different from non-library projects. Anyway just for consideration. LGPL still protects your source code just as GPL does.

**Comment by it4e** [comment]
Right, I will change it to LGPL. @laoshaw
