### ISSUE TITLE
test server needed

### ISSUE THREAD

**Issue by ghost** [it4e/CHL#7]
I would use something like mongoose to add test server for development and testing purposes. It'll reduce installation process to something like:
1. git clone
2. cd CHL
3. make
4. make run_server  (stop_sever, restart_server)
and will not force to install new libs in system path and install and configure Apache, git pull enough for updates, and mongoose is cross platform, header only library (under GPL as well).

**Comment by it4e** [comment]
Good idea. I will have a look at it, if you are not craving for such a task of course. @vadimgit
